//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Csharp_DB_Project.DBq
{
    using System;
    using System.Collections.Generic;
    
    public partial class orderData
    {
        public string Orderer { get; set; }
        public string Orderee { get; set; }
        public int orderID { get; set; }
        public Nullable<int> orderingUserID { get; set; }
        public Nullable<int> companyName { get; set; }
        public string companyType { get; set; }
        public decimal amount { get; set; }
        public decimal price { get; set; }
        public decimal orderAmount { get; set; }
    }
}
