//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Csharp_DB_Project.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewOffer
    {
        public string companyName { get; set; }
        public string companyType { get; set; }
        public decimal amount { get; set; }
        public decimal askingPrice { get; set; }
        public decimal offeramount { get; set; }
        public string offerstatus { get; set; }
        public int offerID { get; set; }
        public Nullable<int> offeringUserid { get; set; }
        public Nullable<int> selleruserID { get; set; }
        public int stockID { get; set; }
    }
}
