//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Csharp_DB_Project.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewAllListing
    {
        public Nullable<int> userID { get; set; }
        public int stockID { get; set; }
        public string companyName { get; set; }
        public string companyType { get; set; }
        public Nullable<decimal> amount { get; set; }
        public decimal price { get; set; }
        public string status { get; set; }
    }
}
